apiVersion: v1
kind: Secret
metadata:
  name: elysia-secrets
type: simmons.studio/secrets
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_PORT: 5432
  DATABASE_NAME: my_db
  TZ: Africa/Lusaka
  NODE_ENV: production