---
version: "3.8"

services:
  api:
    image: simmonsstudiozm/elysia-auth:1
    container_name: elysia
    restart: unless-stopped
    # command: ["bunx", "prisma", "generate", "&&", "bunx", "prisma", "migrate", "deploy"]
    # command: bunx prisma migrate deploy
    entrypoint: bun run src/index.ts
    depends_on:  
      - db
    labels:
      studio.simmons: "Simmons Multimedia Demo"
    environment:
      PORT: '3000'
      TZ: Africa/Lusaka
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: '5432'
      DATABASE_NAME: my_db
      # DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@192.168.0.2:${POSTGRES_PORT}/${DATABASE_NAME}?schema=public
      RESEND_API_KEY: '1234'
    networks:
      docker_net:
        ipv4_address: 192.168.0.1
    ports:
      - "3000:3000"

  db:
    image: postgres:16.2-bullseye
    container_name: elysia_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_PORT: '5432'
      DATABASE_NAME: my_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      docker_net:
        ipv4_address: 192.168.0.2

  pgadmin:
    image: dpage/pgadmin4:8.5
    container_name: elysia_pgadmin
    restart: unless-stopped
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "80:80"
    # command: psql -U ${POSTGRES_USER} -d ${DATABASE_NAME} -f migration_script.sql
    volumes:
      - pgadmin_data:/var/lib/pgadmin/data
    networks:
      docker_net:
        ipv4_address: 192.168.0.4

networks:
  docker_net:
    ipam:
      driver: default
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.100

volumes:
  postgres_data:
  pgadmin_data: