# Use official BunJS image
FROM oven/bun:latest

# Set working directory in container
WORKDIR /usr/src/app

# Copy package files
COPY package*.json bun.lockb ./

# Install dependencies via bun
RUN bun install --production

# Copy app code to container
COPY . .

# Expose app's port
EXPOSE 3000

# Command to run your app
CMD [ "bun", "dev" ]