# use the official Bun image
# see all versions at https://hub.docker.com/r/oven/bun/tags
FROM oven/bun:1.1.6 as base
WORKDIR /usr/src/app


# install dependencies into temp directory
# this will cache them and speed up future builds
FROM base AS install
RUN mkdir -p /temp/dev
COPY package.json bun.lockb /temp/dev/
RUN cd /temp/dev && bun install --frozen-lockfile

# install with --production (exclude devDependencies)
# RUN mkdir -p /temp/prod
# COPY package.json bun.lockb /temp/prod/
# RUN cd /temp/prod && bun install --production


# copy node_modules from temp directory
# then copy all (non-ignored) project files into the image
FROM base AS prerelease
COPY prisma prisma
COPY src src
COPY tsconfig.json tsconfig.json
COPY --from=install /temp/dev/node_modules node_modules
# RUN bunx prisma -v
# RUN chown -R root:root /usr/src/app/node_modules/@prisma
# RUN chmod -R a+x /usr/src/app/node_modules/@prisma
# RUN bunx prisma generate
# Manually copy these folders from host to the root directory
COPY .prisma node_modules/.prisma
COPY @prisma node_modules/@prisma

# [optional] tests & build
ENV NODE_ENV=production
# RUN bun test
# RUN bun run build


# copy production dependencies and source code into final image
# FROM base AS release
# COPY --from=install /temp/prod/node_modules node_modules
# COPY --from=install /temp/dev/node_modules node_modules
# COPY --from=prerelease /usr/src/app/ .
# COPY --from=prerelease /usr/src/app/package.json .

# run the app
USER bun
EXPOSE 3000/tcp

ENTRYPOINT [ "bun", "run", "/usr/src/app/src/index.ts" ]

# execute the binary!
# CMD ["/usr/src/app/app"]