name: Build and Push Elysia Auth Demo Docker Image

on:
  push:
    branches:
      - build

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Check out the repository
    - name: Checkout repository code
      uses: actions/checkout@v3

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    # Build and push the Docker image
    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: simmonsstudiozm/elysia-auth:slim
        platforms: linux/arm64

    # Trigger Portainer webhook to deploy the new image
    - name: Trigger Portainer webhook
      run: |
        curl -X POST \
          -H "Content-Type: application/json" \
          -d '{}' \
          ${{ secrets.PORTAINER_WEBHOOK_URL }}